/*
===============================================================================
                           JAVA ARCHITECTURE
===============================================================================

Author : Vedant
Topic  : JVM, JDK, JRE, Bytecode, Compilation Process

===============================================================================
WHY SHOULD YOU LEARN JAVA ARCHITECTURE?
===============================================================================

Many beginners learn Java syntax before understanding how Java programs
actually execute.

Knowing Java Architecture helps you answer questions like:

• How does Java become platform independent?
• What exactly is JVM?
• What is the difference between JDK and JRE?
• What is Bytecode?
• Why is Java slower than C++ during startup?
• How does Garbage Collection work?

These are among the most frequently asked interview questions.

===============================================================================
THE COMPLETE JAVA EXECUTION FLOW
===============================================================================

                    Developer
                        │
                        ▼
                 Main.java Source Code
                        │
                  javac Compiler
                        │
                        ▼
                 Main.class Bytecode
                        │
              +-----------------------+
              |          JVM          |
              +-----------------------+
              | Class Loader          |
              | Bytecode Verifier     |
              | Execution Engine      |
              | Garbage Collector     |
              +-----------------------+
                        │
                        ▼
                Native Machine Code
                        │
                        ▼
                   Program Executes

===============================================================================
WHAT IS BYTECODE?
===============================================================================

Bytecode is an intermediate language generated by the Java compiler.

It is NOT machine code.

It is NOT Java source code.

Instead, it is platform-independent code that can run on any JVM.

Example

Main.java

↓

javac Main.java

↓

Main.class

The .class file contains bytecode.

Every operating system reads the SAME bytecode.

===============================================================================
WHY BYTECODE?
===============================================================================

Without Bytecode

C++ Program

Windows
↓

Windows EXE

Cannot run on Linux.

--------------------------------------------

With Java

Java Source

↓

Bytecode

↓

Windows JVM
Linux JVM
Mac JVM

Same program.

No recompilation required.

This is called

Write Once Run Anywhere (WORA)

===============================================================================
JDK (JAVA DEVELOPMENT KIT)
===============================================================================

JDK is a complete package used by developers.

It contains everything required to develop Java applications.

Components

• Java Compiler (javac)
• Java Runtime Environment (JRE)
• Debugger
• Documentation Tool
• Jar Tool
• Java Libraries
• JVM

Think of JDK as a toolbox for programmers.

===============================================================================
WHEN DO WE USE JDK?
===============================================================================

You need JDK when you want to

✔ Write Java programs

✔ Compile Java programs

✔ Debug programs

✔ Build applications

If you are a Java developer,

YOU MUST INSTALL JDK.

===============================================================================
JRE (JAVA RUNTIME ENVIRONMENT)
===============================================================================

JRE is used ONLY for running Java programs.

It does NOT contain

• Compiler
• Debugger
• Development Tools

JRE contains

• JVM
• Core Libraries
• Runtime Components

===============================================================================
WHEN DO WE USE JRE?
===============================================================================

Imagine a company distributes software written in Java.

The users do not need the compiler.

They only need to run the application.

For this,

JRE is sufficient.

===============================================================================
JVM (JAVA VIRTUAL MACHINE)
===============================================================================

JVM is the heart of Java.

It is responsible for

✔ Loading classes

✔ Verifying bytecode

✔ Executing code

✔ Managing memory

✔ Garbage Collection

✔ Security

Every Operating System has its own JVM implementation.

Windows JVM

Linux JVM

Mac JVM

All execute the same bytecode.

===============================================================================
JDK vs JRE vs JVM
===============================================================================

JDK
----------------------------------------
Purpose :
Development

Contains :
Compiler + JRE + JVM

Used By :
Developers

----------------------------------------

JRE
----------------------------------------
Purpose :
Execution

Contains :
JVM + Libraries

Used By :
End Users

----------------------------------------

JVM
----------------------------------------
Purpose :
Execute Bytecode

Contains :
Execution Engine

Used By :
Inside JRE

===============================================================================
RELATIONSHIP
===============================================================================

JDK

┌──────────────────────────────┐
│                              │
│      JRE                     │
│   ┌─────────────────────┐    │
│   │                     │    │
│   │       JVM           │    │
│   │                     │    │
│   └─────────────────────┘    │
│                              │
└──────────────────────────────┘

Meaning

JDK contains JRE

JRE contains JVM

===============================================================================
JVM INTERNAL ARCHITECTURE
===============================================================================

                    JVM

          +-------------------+
          | Class Loader      |
          +-------------------+
                    │
                    ▼
          +-------------------+
          | Bytecode Verifier |
          +-------------------+
                    │
                    ▼
          +-------------------+
          | Execution Engine  |
          +-------------------+
             │           │
             │           ▼
             │      JIT Compiler
             │
             ▼
       Machine Code

                    │

          Garbage Collector

===============================================================================
CLASS LOADER
===============================================================================

Class Loader loads

.class

files into memory.

Responsibilities

• Finds class files

• Loads them

• Links them

• Initializes them

Without Class Loader,

Java cannot execute any class.

===============================================================================
BYTECODE VERIFIER
===============================================================================

Checks whether bytecode is safe.

It prevents

• Illegal memory access

• Invalid instructions

• Corrupted bytecode

This is one reason Java is secure.

===============================================================================
EXECUTION ENGINE
===============================================================================

Reads bytecode.

Converts it into machine code.

Executes the instructions.

Initially,

Java used only an Interpreter.

Modern JVMs use

Interpreter

+

JIT Compiler

===============================================================================
INTERPRETER
===============================================================================

Reads bytecode

One instruction at a time.

Advantages

Simple

Fast startup

Disadvantages

Repeated execution becomes slow.

===============================================================================
JIT (JUST-IN-TIME) COMPILER
===============================================================================

JIT detects frequently executed code.

It compiles that bytecode into native machine code.

Next time,

the program executes much faster.

Example

Loop executed 1 million times

↓

Interpreter notices repeated execution

↓

JIT compiles it

↓

Native execution

↓

Huge performance improvement

===============================================================================
GARBAGE COLLECTION
===============================================================================

Java automatically removes objects

that are no longer being used.

Programmer does NOT manually free memory.

Benefits

✔ Fewer memory leaks

✔ Safer applications

✔ Cleaner code

Example

Person p = new Person();

p = null;

Object becomes unreachable.

Garbage Collector eventually removes it.

===============================================================================
JAVA MEMORY AREAS (Overview)
===============================================================================

JVM Memory

+----------------------------+
| Method Area                |
+----------------------------+
| Heap                       |
+----------------------------+
| Java Stack                 |
+----------------------------+
| PC Register                |
+----------------------------+
| Native Method Stack        |
+----------------------------+

We'll study these in detail later.

===============================================================================
COMPILATION VS EXECUTION
===============================================================================

Compilation

Source Code

↓

Bytecode

Performed once.

Uses javac.

--------------------------------------------

Execution

Bytecode

↓

Machine Code

Performed every run.

Uses JVM.

===============================================================================
REAL-WORLD ANALOGY
===============================================================================

Imagine you write a book in English.

Different translators convert it into

French

German

Spanish

Japanese

Similarly,

Java Compiler creates Bytecode.

Different JVMs translate Bytecode into machine code for each operating system.

The original Java source remains unchanged.

===============================================================================
COMMON INTERVIEW QUESTIONS
===============================================================================

Q1. What is Bytecode?

Platform-independent intermediate code generated by javac.

--------------------------------------------------

Q2. Why is Java platform independent?

Because bytecode runs on JVMs available for different operating systems.

--------------------------------------------------

Q3. Difference between JDK and JRE?

JDK = Development

JRE = Execution

--------------------------------------------------

Q4. Does JDK contain JVM?

Yes.

--------------------------------------------------

Q5. Does JRE contain Compiler?

No.

--------------------------------------------------

Q6. Can Java run without JVM?

No.

JVM is mandatory for executing bytecode.

--------------------------------------------------

Q7. What is JIT Compiler?

A compiler inside JVM that converts frequently executed bytecode into native
machine code for better performance.

===============================================================================
QUICK REVISION
===============================================================================

✔ Java Source → .java

✔ Compiler → javac

✔ Bytecode → .class

✔ JVM executes bytecode

✔ JDK = JRE + Development Tools

✔ JRE = JVM + Libraries

✔ JVM = Execution Engine

✔ Bytecode enables WORA

✔ JIT improves performance

✔ Garbage Collector manages memory automatically

===============================================================================
NEXT TOPIC
===============================================================================

03_IdentifiersAndVariables.java

Topics:
• Identifiers
• Variables
• Declaration
• Initialization
• Scope
• Lifetime
• Naming Conventions
• Constants (final)
• Type Inference (var)
• Best Practices
• Common Mistakes

===============================================================================